### ISSUE TITLE
[Suggestion] Option to change character voice

### ISSUE THREAD

**Issue by Rueby** [Ottermandias/Glamourer#28]
Is it possible to add this into the customization somehow? It'd be nice to mix and match sounds for example male viera on male elezen model etc.

**Comment by Ottermandias** [comment]
Nope, not at all.

**Comment by PassiveModding** [comment]
Just wanted to check, is it possible to add voice as an option for the current race?

Currently, if you change to another race your voice is stuck as whatever it defaults to or the same index for voice as your actual character.
I'd like to see an option to select between the voices for the race, to mimic the option in the character creator, rather than mix and match as was suggested above
